


GlobalMsg = {
    "ON_DISPOSE_LUA_ENV",

    "ON_LUA_DEBUG_SOCKET_MESSAGE",
    "SYNC_CLIENT_REMOTE_TASK",

    "ON_NET_MASK_CHANGED",

    "INIT_LUA_SYSTEM_MANAGER",
    "RELEASE_LUA_SYSTEM_MANAGER",

    "ON_UI_PHASE_OPENED",
    "ON_UI_PHASE_EXITED",

    "RECOVER_PHASE_LEVEL",
    "ON_PHASE_LEVEL_ON_TOP",
    "ON_PHASE_LEVEL_NOT_ON_TOP",
    "ON_CONTROLLER_INDICATOR_CHANGE",
    "ON_INPUT_DEVICE_TYPE_CHANGED",
    "ON_TRY_CHANGE_INPUT_DEVICE_TYPE",
    "ON_CONFIRM_CHANGE_INPUT_DEVICE_TYPE",
    "ON_CONTROLLER_TYPE_CHANGED",
    "SHOW_INPUT_DEVICE_CHANGE_POPUP",

    "ON_FAC_TOP_VIEW_HIDE_UI_MODE_CHANGE",
    "FAC_ON_DRAG_BEGIN_IN_BATCH_MODE",
    "FAC_ON_DRAG_END_IN_BATCH_MODE",
    "FAC_ON_TOGGLE_BATCH_MODE",
    "FAC_ON_TOGGLE_BATCH_TARGET",

    "FAC_STOP_DRAG_IN_BATCH_MODE",

    "CHANGE_MOUSE_ICON_HINT",

    "START_COMMON_BLACK_OUT",

    "ADD_COMMON_BLOCK_MASK",
    "REMOVE_COMMON_BLOCK_MASK",

    "CAMERA_HIDE_HUD",
    "CAMERA_END_HIDE_HUD",

    "TOGGLE_HIDE_FAC_TOP_VIEW_RIGHT_SIDE_UI",

    "INTERRUPT_MAIN_HUD_ACTION_QUEUE",
    "ON_ONE_MAIN_HUD_ACTION_FINISHED",
    "ALL_MAIN_HUD_ACTION_FINISH",
    "COMMON_START_BLOCK_MAIN_HUD_ACTION_QUEUE",
    "COMMON_END_BLOCK_MAIN_HUD_ACTION_QUEUE",
    "MAIN_HUD_ACTION_QUEUE_TOGGLE_IGNORE_MAIN_HUD_CS",
    "TOGGLE_IN_MAIN_HUD_STATE",

    "ON_SHOW_INPUT_FIELD_BG",
    "ON_INPUT_FIELD_BG_HEIGHT_CHANGE",

    "ON_PREPARE_NARRATIVE",
    "ON_NARRATIVE_BLACK_SCREEN_END",

    "OPEN_INVENTORY_PANEL",

    "ON_RESET_BLACKBOX",

    "OPEN_PUZZLE_PANEL",
    "PUZZLE_UNIT_COMPLETE",
    "ON_BLOCK_PICKUP",

    "ON_COMMON_BLEND_IN",
    "INTERRUPT_MAIN_HUD_ACTION_ON_COMMON_BLEND_IN",
    "ON_COMMON_BLEND_OUT",

    "OPEN_PHASE_FOR_CS",

    "SHOW_COMMON_TIPS",

    "OVERRIDE_JUMP_ACTION",

    "ON_IN_MAIN_HUD_CHANGED",

    "SET_MAIN_HUD_CAN_AUTO_STOP_EXPAND",

    "SHOW_FOCUS_MODE_TOAST",
    "ENTER_FOCUS_MODE_READY",
    "TOGGLE_FORBID_CHAR_FOOT_BAR",
    "TRY_SWITCH_FAC_MODE",
    "SHOW_COMMON_TITLE_TIPS",
    "HIDE_COMMON_TITLE_TIPS",

    "ATTACH_DUMMY_NAVI_LAYER",
    "DETACH_DUMMY_NAVI_LAYER",

    
    "ON_WAIT_MSG_EXECUTE_COMPLETE",
    "SHOW_COMMON_SHARE_PANEL",
    "ON_SHARE_END",
    "ON_OPEN_FRIENDLY_TIPS",
    

    
    "SHOW_ENTER_FOCUS_MODE_CONFIRM",
    

    
    "ON_HUD_LAYOUT_LOADED",
    "ON_HUD_LAYOUT_SAVED",
    "ON_HUD_LAYOUT_CHANGED",
    

    
    "GENDER_SELECT_START",
    "ON_CONFIRM_GENDER",
    "GENDER_SELECT_ACTIVE_NOTIFICATION",
    "GENDER_CHANGE_START",
    

    
    "SET_PLAYER_NAME_START",
    "ON_CHECK_PLAYER_NAME_FAILED",
    "ON_CHECK_PLAYER_NAME_SUCCESS",
    "ON_SET_PLAYER_NAME",
    

    
    "SHOW_SPACESHIP_CHAR_TIPS",
    "HIDE_SPACESHIP_CHAR_TIPS",
    "HIDE_SPACESHIP_CHAR_TIPS_DONE",

    "OPEN_SPACESHIP_SHOWCASE_PANEL",
    "OPEN_SPACESHIP_CONTROL_CENTER",
    "SPACESHIP_ON_SHOWCASE_MODIFY",

    "SPACESHIP_ON_SYNC_ROOM_STATION",
    "ON_CHAR_FRIENDSHIP_CHANGED",
    "ON_CHAR_GIFT_INFO_CHANGED",
    "ON_RECV_CHAR_GIFT",
    "ON_CHAR_FRIENDSHIP_SEND_CHAR_GIFT_SUCCESS",
    "ON_SPACESHIP_MANUFACTURING_STATION_SYNC",
    "ON_SPACESHIP_MANUFACTURING_STATION_START",
    "ON_SPACESHIP_MANUFACTURING_STATION_COLLECT",
    "ON_SPACESHIP_MANUFACTURING_STATION_CANCEL",
    "SPACESHIP_ON_ROOM_ADDED",
    "SPACESHIP_ON_ROOM_INFO_UPDATED",
    "SPACESHIP_ON_ROOM_LEVEL_UP",
    "SPACESHIP_ON_ROOM_LOCKED_CHANGED",
    "SPACESHIP_ON_ROOM_DATA_CHANGE",
    "ON_SPACESHIP_LEVEL_START",
    "ON_SPACESHIP_GROW_CABIN_HARVEST",
    "ON_SPACESHIP_GROW_CABIN_MODIFY",
    "ON_SPACESHIP_GROW_CABIN_SOW",
    "ON_SPACESHIP_GROW_CABIN_CANCEL",
    "ON_SPACESHIP_GROW_CABIN_BREED",
    "SPACESHIP_ROOM_SERIAL_NUM_CHANGE",
    "ON_SPACESHIP_RECV_QUERY_VISIT_INFO",
    "SPACESHIP_ON_ROOM_DECONSTRUCT",
    "ON_CHANGE_SPACESHIP_DOMAIN_ID",
    "SPACESHIP_ON_SET_ROOM_STATION_SUCC",
    "ON_INT_SPACESHIP_ROOM",
    "ON_SPACESHIP_HEAD_NAVI_TARGET_CHANGE",
    "ON_CLICK_SPACESHIP_VISITOR_FRIEND",
    "ON_INT_SS_CHAR_POSTER",
    "ON_INT_SS_WEAPON_POSTER",
    "ON_INT_SS_SCREEN_POSTER",

    "ON_READ_NEW_SS_PICTURE",

    "ON_SPACESHIP_VISIT_FRIEND",
    "ON_SPACESHIP_HELP_ROOM",
    "ON_SPACESHIP_USE_HELP_CREDIT",
    "ON_SPACESHIP_ASSIST_DATA_MODIFY",

    "SET_SPACESHIP_CHAR_POSTER",
    "SET_SPACESHIP_WEAPON_POSTER",
    "SET_SPACESHIP_SCREEN_POSTER",
    "SET_SPACESHIP_CHAR_POSTER_SERIAL_NUMBER",
    "ON_SPACESHIP_GUEST_ROOM_WEAPON_CHANGE",
    "ON_SPACESHIP_GUEST_ROOM_CHAR_CHANGE",
    "ON_SPACESHIP_GUEST_ROOM_SET_CHAR_PICTURE_LIST",
    "ON_SPACESHIP_GUEST_ROOM_RECV_VISIT_LIST_REWARD",

    "ON_SPACESHIP_RECV_CLUE",
    "ON_SPACESHIP_RECV_FRIEND_CLUE",
    "ON_SPACESHIP_PRESENT_FRIEND_CLUE",
    "ON_SPACESHIP_CLUE_PLACE_CHANGE",
    "ON_SPACESHIP_OPEN_INFO_EXCHANGE",
    "ON_SPACESHIP_JOIN_FRIEND_INFO_EXCHANGE",
    "ON_SPACESHIP_GUEST_ROOM_CLUE_REWARD_ITEM",
    "ON_POP_SPACESHIP_GUEST_ROOM_MAIN_PANEL",
    "ON_PUSH_SPACESHIP_GUEST_ROOM_MAIN_PANEL",
    "ON_SPACESHIP_GUEST_ROOM_CLUE_EXCHANGE_EXPIRE",
    "ON_SPACESHIP_CLUE_INFO_CHANGE",
    "ON_SPACESHIP_CLUE_INFO_SYNC",
    "ON_SPACESHIP_SELF_CLUE_DELETE",
    "ON_SPACESHIP_CLUE_FULL",
    "ON_CLUE_EXPIRE",

    
    "SS_REGISTER_STATUS_BAR",
    "SS_REGISTER_CHAR_INFO_PANEL",
    "SS_UNREGISTER_STATUS_BAR",
    "SS_UNREGISTER_CHAR_INFO_PANEL",
    

    
    "ON_START_WEB_APPLICATION",
    "ON_CLOSE_WEB_APPLICATION",
    "ON_ANNOUNCEMENT_RED_DOT_CHANGED",
    "ON_SERVER_ZONE_CHANGED",
    "ON_SDK_MASK_HIDE",
    "ON_QUERY_UNREAD_MSG", 
    "ON_CLOSE_CUSTOMER_SERVICE", 
    

    
    "ON_GACHA_SUCC",
    "ON_GACHA_POOL_INFO_CHANGED",
    "ON_GACHA_POOL_ROLE_DATA_CHANGED",
    "ON_ACTIVITY_GACHA_BEGINNER_STAGE_MODIFY",

    "ON_GACHA_TESTIMONIAL_CONVERT",
    
    "GACHA_POOL_ADD_SHOW_REWARD",
    "ON_ONE_GACHA_POOL_REWARD_FINISHED",
    "GACHA_WEAPON_POOL_ADD_SHOW_REWARD",
    "ON_ONE_GACHA_WEAPON_POOL_REWARD_FINISHED",

    "ON_GACHA_POOL_NEW_OPENED_READ",

    "INNER_GACHA_RESULT_ON_SHARE_CAPTURE",
    

    
    "ON_CHARACTER_TRIAL_INFO_CHANGE",
    


    
    "SHOW_GACHA_WEAPON_TEN",
    "SHOW_GACHA_WEAPON_ONCE",
    

    "FAC_UPDATE_INTERACT_OPTION",
    "FAC_TOGGLE_SUB_BUILDING_OPT_USE_INDEX_NAME_FOR_GUIDE",
    "FAC_BLOCK_OTHER_HUB_UNLOADER_INTERACT",
    "FAC_ON_MODIFY_CHAPTER_SCENE",

    "ON_CONTROLLER_NAVI_TARGET_CHANGED",
    "ON_PANEL_ORDER_RECALCULATED",

    "ON_ITEM_BAG_ABANDON_IN_BAG_SUCC",
    "ON_ITEM_BAG_TOGGLE_ABANDON_DROP",
    "TOGGLE_DROP_ITEM_VISIBLE",

    "TOGGLE_COMMON_ITEM_TOAST_CACHE",

    "FAC_SHOW_FORMULA",
    "FAC_SHOW_UNLOADER_SELECT",
    "FAC_FORCE_CULLING",

    "ON_TRIGGER_PLAYER_ACTION",

    "SHOW_AS_CONTROLLER_SMALL_MENU",
    "CLOSE_CONTROLLER_SMALL_MENU",

    "CLOSE_LOGIN_PANEL",
    "ON_PRELOAD_START",
    "OPEN_LOADING_PANEL",
    "OPEN_TELEPORT_LOADING_PANEL",
    "CLOSE_LOADING_PANEL",
    "ON_LOADING_PANEL_OPENED",
    "ON_LOADING_PANEL_CLOSED",
    "ON_TELEPORT_LOADING_PANEL_OPENED",
    "ON_TELEPORT_LOADING_PANEL_CLOSED",
    "ADD_LOADING_SYSTEM",
    "REMOVE_LOADING_SYSTEM",
    "START_CAMERA_RENDER_IN_LOADING",
    "ON_CLICK_LOGIN",
    "ENTER_MAIN_GAME",
    "ON_SCENE_LOAD_START",
    "PRE_LEVEL_START",
    "OPEN_LEVEL_PHASE",
    "ON_MAIN_TARGET_CHANGED",
    "ON_LOCK_TARGET_CHANGED",
    "ON_BREAKING_TARGET_CHANGED",
    "ON_LOGIN_CHECK_INTERRUPT",
    "ON_LOGIN_RESUME",

    "ON_SCREEN_SIZE_CHANGED",

    "FAC_TOGGLE_TOP_VIEW",
    "SET_FAC_TOP_VIEW_CUSTOM_RANGE",
    "FAC_TOGGLE_TOP_VIEW_BUILDING_INFO",
    "FAC_UPDATE_TOP_VIEW_BUILDING_INFOS",
    "ON_FAC_TOP_VIEW_CAM_ZOOM",

    "FAC_ON_SAVE_BLUEPRINT",
    "FAC_ON_MODIFY_BLUEPRINT",
    "FAC_ON_DELETE_BLUEPRINT",
    "FAC_ON_PENDING_NODE_CHANGED",
    "FAC_ON_PENDING_NODE_SLOT_SUBMIT_ITEM_CHANGED",
    "FAC_ON_PENDING_SLOTS_REMOVED",
    "FAC_ON_READ_BLUEPRINT",
    "FAC_ON_REVIEW_BLUEPRINT",
    "FAC_ON_SHARE_BLUEPRINT",
    "FAC_ON_FETCH_BLUEPRINT",
    "FAC_ON_QUERY_SHARED_BLUEPRINT",
    "FAC_ON_GET_GIFT_BLUEPRINT",
    "FAC_ON_REFRESH_SHARE_STATE",
    "FAC_QUERY_BLUEPRINT_TIME_OUT",

    "FAC_MAIN_HUD_CLOSE_MOBILE_BOX",
    "FAC_MAIN_HUD_RIGHT_STOP_FOCUS",

    "SHOW_ITEM_TIPS",
    "HIDE_ITEM_TIPS",
    "TOGGLE_ITEM_TIPS_AUTO_CLOSE",
    "ON_SET_IN_SAFE_ZONE",
    "ON_CHANGE_HIGHLIGHT_BUILDING_RESP",
    "ON_BUILDING_LINKED_TO_POWER",

    "MOVE_LEVEL_CAMERA",
    "TOGGLE_LEVEL_CAMERA_MOVE",
    "ZOOM_LEVEL_CAMERA",

    "ON_TOGGLE_INTERACT_OPTION_SCROLL",
    "FOCUS_ON_INTERACT_OPTION",
    "TOGGLE_PLAYER_MOVE",
    "ON_TOGGLE_UI_ACTION",
    "AFTER_TOGGLE_UI_ACTION",
    "ON_LUA_INIT_FINISHED",
    "ON_START_UI_DRAG",
    "ON_END_UI_DRAG",

    "CS_SHOW_HYPERLINK_POPUP",
    "SHOW_HYPERLINK_POPUP_BY_GROUP_ID",
    "SHOW_HYPERLINK_TIPS",
    "HIDE_HYPERLINK_TIPS",

    "ON_BATTLE_SQUAD_CHANGED",
    "ON_MARK_TARGET_CHANGED",
    "ON_CONFIRM_TARGET_CHANGED",
    "ON_MARKER_COLOR_CHANGED",

    "SHOW_POWER_POLE_LINKING_LABEL",
    "HIDE_POWER_POLE_LINKING_LABEL",
    "UPDATE_POWER_POLE_LINKING_LABEL",
    "SHOW_POWER_POLE_TOAST",

    "ON_CARGO_LOADED_TO_REPOSITORY",
    "ON_CARGO_UNLOADED_FROM_REPOSITORY",
    "ON_QUICK_BAR_CHANGED",
    "FAC_TOGGLE_CAN_DEACTIVE_QUICK_BAR",
    "ON_NEW_SCOPE_INFO_RECEIVED",
    "ON_GAME_LOGIC_INIT_FINISHED",
    "ON_FINISH_WORKSHOP_CRAFT",
    "ON_ITEM_BAG_CHANGE", 
    "FAC_ON_CONSUMING_POWER",
    "ON_TOGGLE_SPRINT",
    "TOGGLE_FORBID_ATTACK",
    "ON_ITEM_BAG_FULL",
    "FAC_ON_NO_REST_POWER",
    "FAC_ON_BUILDING_UPGRADE",
    "ON_UI_PANEL_CLOSED",
    "ON_UI_PANEL_OPENED",
    "ON_UI_PANEL_START_OPEN",
    "ON_BEFORE_UI_PANEL_OPEN",
    "ON_UI_PANEL_SHOW",
    "ON_UI_PANEL_HIDE",
    "CLOSE_UI_PANEL",

    
    
    
    
    "ON_SYSTEM_UNLOCK_CHANGED",

    "ON_ALL_SYSTEM_UNLOCK_SYNC",

    "ON_SYSTEM_UNLOCK_FOR_GUIDE",
    "START_GUIDE_STEP",
    "ON_FINISH_GUIDE_GROUP",
    "SHOW_GUIDE_SLIDE_SCREEN_PANEL",
    "HIDE_GUIDE_SLIDE_SCREEN_PANEL",
    "ON_IN_FACTORY_MAIN",
    "ON_FAC_BELT_DRAW_COMPLETE",
    "ON_GRID_BELT_ADDED_BY_PATH",
    "FAC_ON_BUILDING_CONNECT",
    "SHOW_FAC_QUICK_BAR",
    "HIDE_FAC_QUICK_BAR",
    "PLAY_FAC_QUICK_BAR_OUT_ANIM",
    "START_SET_BUILDING_ON_FAC_QUICK_BAR",
    "START_SWITCH_SLOT_ON_FAC_QUICK_BAR",
    "NAVI_TO_FAC_QUICK_BAR",
    "QUICK_DROP_TO_FAC_QUICK_BAR",
    "ON_BLOCK_KEYBOARD_EVENT_PANEL_ORDER_CHANGED",
    "SHOW_BLOCK_INPUT_PANEL",

    "TOGGLE_FAC_MAIN_NAVIGATION_FROZEN_STATE",
    "FAC_MAIN_NAVIGATION_STATE_CHANGE",
    "FAC_MAIN_NAVIGATION_STATE_CHANGE_QUICK_BAR",

    "ON_TOGGLE_VIRTUAL_MOUSE",

    "SHOW_NAVI_TARGET_ACTION_MENU",
    "HIDE_NAVI_TARGET_ACTION_MENU",

    "FAC_ENTER_BUILDING_MODE",
    "FAC_ENTER_BELT_MODE",
    "FAC_BELT_MODE_MOUSE_HOVER",
    "BEFORE_ENTER_DESTROY_MODE",
    "BEFORE_EXIT_DESTROY_MODE",
    "FAC_ENTER_DESTROY_MODE",
    "FAC_EXIT_DESTROY_MODE",
    "FAC_EXIT_DESTROY_MODE_FOR_CS",
    "FAC_SWITCH_BUILDING_TARGET_DISPLAY_MODE",
    "ON_FAC_DESTROY_MODE_CHANGE",
    "ON_INTERACT_CONVEYOR_LOCAL_CHECKING_FAILED",
    "ON_CONVEYOR_CHANGE",
    "ON_PORT_BLOCK_STATE_CHANGE",

    "ON_EXIT_TRAVEL_MODE",

    "ON_ENTER_LIQUID_POOL_NEARBY_AREA",
    "ON_LEAVE_LIQUID_POOL_NEARBY_AREA",
    "SHOW_LIQUID_POOL",

    "SHOW_COMMON_FILTER",

    "ON_CHAR_NEW_TAG_CHANGED",
    "ON_RESET_LEVEL",
    "ON_SCENE_GRADE_CHANGE_NOTIFY",
    "ON_INITIALIZE_REGION_MAP_CONTROLLER",
    "ON_MAP_REMIND_UPDATE",
    "REFRESH_MAP",
    "SHOW_MARK_INFO",
    "CLOSE_MARK_INFO",
    "SWITCH_TO_REGION_MAP",
    "SWITCH_DOMAIN_MAP",
    "SWITCH_TO_LEVEL_MAP",
    "ON_CLICK_MAP_CLOSE_BTN",
    "CLOSE_MAP",
    "ON_SHOW_MAP_ITEM_LIST",
    "ON_HIDE_MAP_ITEM_LIST",
    "SHOW_LEVEL_MAP_FILTER",
    "HIDE_LEVEL_MAP_FILTER",
    "ON_SHOW_MAP_OTHER_TRACK",
    "ON_HIDE_MAP_OTHER_TRACK",
    "ON_LEVEL_MAP_SWITCH_BTN_CLICKED",
    "ON_LEVEL_MAP_MARK_CLICKED",
    "ON_MAP_POWER_LINE_CHANGED",
    "ON_MAP_TRAVEL_LINE_CHANGED",
    "ON_MAP_UD_PIPE_LINE_CHANGED",
    "ON_MAP_MARK_RUNTIME_DATA_CHANGED",
    "ON_MAP_MARK_RUNTIME_DATA_MODIFY",
    "ON_MAP_TRACKING_MISSION_DATA_CHANGED",
    "ON_MAP_TRACKING_DIFF_LEVEL_STATE_CHANGED",
    "ON_MAP_TRACKING_DIFF_LEVEL_PORT_CHANGED",
    "ON_MAP_DETECTOR_ENTITY_CHANGE",
    "ON_MAP_DETECTOR_SHOW_MAP",
    "SHOW_LEVEL_MAP_MARK_DETAIL",
    "HIDE_LEVEL_MAP_MARK_DETAIL",
    "ON_CLICK_REGIONMAP_LEVEL_BTN",
    "ON_CLICK_REGIONMAP_LOCK",
    "ON_MAIN_CHARACTER_CHANGE",
    "ON_INTERACT_NPC",
    "ON_BUILD_MODE_CHANGE",
    "BEFORE_ENTER_BUILD_MODE",
    "OPEN_FAC_BUILD_MODE_SELECT",
    "FAC_LOCK_BUILD_POS",
    "SHOW_TOAST",
    "SHOW_SPECIAL_TOAST",
    "SHOW_SYSTEM_TOAST",
    "SHOW_FORMULA_TOAST",
    "TOGGLE_COMMON_ITEM_TOAST",
    "ON_ENABLE_COMMON_TOAST",
    "ON_DISABLE_COMMON_TOAST",
    "SHOW_MAP_NAME_TOAST",
    "ON_MAP_FILTER_STATE_CHANGED",
    "ON_MAP_GAMEPLAY_AREA_ADDED",
    "ON_MAP_GAMEPLAY_AREA_REMOVED",
    "FORCE_SET_OPENED_MAP_LEVEL",
    "SHOW_CUSTOM_MARK_MULTI_DELETE",
    "HIDE_CUSTOM_MARK_MULTI_DELETE",
    "TOGGLE_CUSTOM_MARK_MULTI_DELETE_STATE",
    "ON_CUSTOM_MARK_MULTI_DELETE_SELECT_STATE_CHANGED",
    "ON_CUSTOM_MARK_MULTI_DELETE_SELECT",
    "ON_TRACK_MARK_CHANGE",
    "SELECT_MAP_MARK",
    "TOGGLE_DEBUG_DAMAGE_TEXT_MODE",

    "ON_FIRST_GOT_ITEM",
    "ON_ADD_NEW_ITEM",
    "ON_READ_NEW_ITEM",
    "ON_READ_NEW_INST_ITEM",

    "ON_EXIT_BLOCKED_REWARD_POP_UP_PANEL",
    "ON_ENTER_BLOCKED_REWARD_POP_UP_PANEL",

    "ON_CHAR_JOIN_BY_MAINLINE",

    "SHOW_EXP_TOAST",
    "SHOW_LEVEL_COLLECTION_TOAST",
    "SHOW_LEVEL_COLLECTION_TOAST_SIMPLE",
    "ON_SP_CHANGED",
    "TOGGLE_LUA_CONSOLE",
    "DEV_ONLY_TOGGLE_PANEL",
    "ON_TOGGLE_DEBUG_FLY",
    "ON_CHARACTER_DEAD",
    "ON_COMMON_MASK_HIGH_START",
    "ON_COMMON_MASK_LOW_START",
    "ON_COMMON_MASK_END",
    "ON_COMMON_MASK_LOW_END",
    "ON_COMMON_MASK_SHUTDOWN",
    "ON_COMMON_MASK_LOW_SHUTDOWN",
    "ON_SPECIFIC_MASK_START",
    "ON_ENTITY_LOADED",

    "BLOCK_LUA_UI_INPUT",
    "TOGGLE_DEBUG_INPUT_RECORD",

    "ON_GAIN_ATB",
    "ON_SPECIFIC_BUFF_CHANGED",
    "ON_SQUAD_TACTICAL_ITEM_CHANGE",
    "ON_SQUAD_KILL_ENEMY",
    "ON_TACTICAL_ITEM_CHANGE",
    "FAC_ENTER_LOGISTIC_MODE",
    "FAC_ENTER_BLUEPRINT_MODE",
    "ON_ENTER_BUILDING_MODE",
    "ON_ENTER_BELT_MODE",
    "ON_ENTER_LOGISTIC_MODE",
    "ON_EXIT_BUILDING_MODE",
    "ON_EXIT_BELT_MODE",
    "ON_EXIT_LOGISTIC_MODE",
    "ON_ENTER_BLUEPRINT_MODE",
    "ON_FAC_REGION_START",
    "SHOW_BLUEPRINTS_UNLOCK_HINT",
    "SHOW_REWARDS_POPUP_CENTER",
    "SHOW_REWARDS_POPUP_CENTER_BY_REWARD_ID",
    "CACHE_REWARDS_POPUP",
    "SHOW_CACHED_REFUND_POPUP",
    "SHOW_CRAFT_REWARDS",
    "SHOW_SYSTEM_REWARDS",
    "CS_SHOW_SYSTEM_REWARDS",
    "ON_BUILDING_ADDED_FOR_GUIDE",
    "ON_BUILDING_DATA_REPLACED",
    "ON_SET_BUILDING_MODEL_POSITION",
    "FAC_TOGGLE_MACHINE_TARGET",

    "ON_HUB_CRAFT_SUCC",
    "ON_SCENE_COLLECTION_MODIFY",
    "ON_SCENE_COLLECT_NEW_OBJECT",
    "SHOW_DUNGEON_TOAST",

    "SHOW_CASH_SHOP_TOAST",

    
    "SHOW_AI_BARK",
    "STOP_AI_BARK",
    

    
    "FAC_OPEN_BUILDING_PANEL",
    "FAC_OPEN_BUILDING_PANEL_ALTER",
    "FAC_OPEN_LOGISTIC_PANEL",
    "FAC_ON_REGION_UNLOCKED",

    "FAC_SET_ENABLE_CONFIRM_BUILD",
    "FAC_SET_ENABLE_EXIT_BUILD_MODE",
    "FAC_SET_ENABLE_EXIT_FACTORY_MODE",
    "FORCE_SET_FAC_MODE",
    "FAC_OPEN_NEAREST_BUILDING_PANEL",

    "FAC_ON_PLAYER_POS_INFO_CHANGED",

    "FAC_ON_MOVE_TO_IN_CACHE_SLOT_HINT_START",
    "FAC_ON_MOVE_TO_IN_CACHE_SLOT_HINT_END",
    "FAC_ON_MOVE_SHOW_CONTROLLER_MODE_HINT",
    "FAC_ON_MOVE_HIDE_CONTROLLER_MODE_HINT",

    "FAC_SCROLL_TO_BUILDLIST_TARGET_ITEM",
    "FAC_NAVI_TO_MIXPOOL_TARGET_ITEM",
    

    "ON_TOGGLE_QUICK_BAR_CONTROLLER",

    
    "ON_COMPLETE_GUIDE_GROUP",
    "SHOW_GUIDE_STEP",
    "HIDE_GUIDE_STEP",
    "CLEAR_GUIDE_STEP",
    "START_GUIDE_GROUP",
    "SHOW_GUIDE_EMPTY_MASK",
    "SHOW_GUIDE_MEDIA",
    "HIDE_GUIDE_MEDIA",
    "SHOW_LIMITED_GUIDE",
    "CLEAR_LIMITED_GUIDE",
    "ON_LIMITED_GUIDE_WIKI_ENTRY_READ_STATE_CHANGE",
    "ON_GUIDE_STOPPED",
    "ON_GUIDE_PREPARE_NARRATIVE",
    "ON_GUIDE_LEAVE_NARRATIVE",
    "ON_INTERRUPT_GUIDE",
    "GUIDE_EQUIP_PRODUCE_SCROLL_TO_ITEM",
    "GUIDE_CHAR_INFO_WEAPON_SCROLL_TO_TOP",
    "GUIDE_CHAR_INFO_CHANGE_CHAR",
    

    "CLEAR_SCREEN_ON",
    "CLEAR_SCREEN_OFF",
    "CLEAR_SCREEN_ON_EXCEPT_SOME_PANEL",
    "CLEAR_SCREEN_OFF_EXCEPT_SOME_PANEL",
    "ON_CLEAR_SCREEN_STATE_CHANGED",
    "SHOW_POP_UP",
    "SHOW_POP_UP_CS",
    "HIDE_POP_UP",
    "ON_CREATE_FLOW_TEXT",
    "ON_IGNITE_BUFF_TEXT",
    "ON_PHYSICAL_INFLICTION_APPLIED",
    "ON_ADD_HEAD_BAR",
    "ON_REMOVE_HEAD_BAR",
    "ON_ADD_HEAD_LABEL",
    "ON_REMOVE_HEAD_LABEL",
    "UPDATE_HEAD_LABEL_ICON",
    "ON_ENEMY_PART_ENABLE",
    "ON_ENEMY_PART_DISABLE",

    "ON_TRADER_NEW_ORDER_GENERATED",
    "ON_ORDER_REMOVING",
    "ON_TRADER_CONTRACT_ID_CHANGED",
    "ON_ORDER_COMPLETE",
    "ON_MANUFACT_TARGET_CRAFT_ID_CHANGED",
    "ON_RECYCLER_MODIFY",
    "ON_RECYCLER_GET_ITEMS",
    "ON_RECYCLER_COMMIT_MATERIAL",
    "ON_BUILDING_ACTIVED_CHANGED",
    "SQUAD_CHANGE",
    "SQUAD_NAME_CHANGE",
    "CHANGE_ACTIVE_SQUAD",
    "CHAR_NORMAL_SKILL_CHANGE",
    "TEAM_NORMAL_SKILL_CHANGE",
    "ON_BUILDING_UPGRADED",
    "ON_BUILDING_ASSIGN_CHARACTER_CHANGED",
    "ON_CAMPFIRE_OPEN_FORMATION",
    "ON_SQUAD_INFIGHT_CHANGED",
    "ON_ESCAPE_FROM_FIGHT",
    "ON_POISE_CHANGE",
    "ON_CLOSE_BLOC_PANEL",
    "ON_BLOC_CHANGE",
    "ON_SYNC_ALL_BLOC",
    "AFTER_ON_BUY_ITEM_SUCC",
    "ON_SQUAD_ICON_ACTIVE_CONFIG_CHANGED",
    "ON_SKILL_BUTTON_ACTIVE_CONFIG_CHANGED",
    "ON_SWITCH_MAIN_CHAR_ENABLE_CONFIG_CHANGED",

    "ON_BLOC_REWARD_RESP",
    "UPDATE_GENERAL_TRACKER",
    "ON_GOLD_CHANGE",
    "ON_BLOC_TOKEN_CHANGE",
    "ON_BLOC_SHOP_CHANGE",
    "ON_ENTER_WORLD_BUILD",
    "FAC_BUILD_EXIT_CUR_MODE",
    "FAC_BUILD_EXIT_CUR_MODE_FOR_CS",

    "FAC_ON_BELT_UNLOCKED",
    "FAC_ON_PIPE_UNLOCKED",

    "TRAVEL_POLE_ENTER_TRAVEL_MODE",
    "TRAVEL_POLE_TRAVEL_ON_ENTER",
    "TRAVEL_POLE_TRAVEL_ON_REACH",
    "TRAVEL_POLE_TRAVEL_ON_REACH_REFRESH",
    "TRAVEL_POLE_FAST_EXIT",
    "TRAVEL_POLE_SHOW_QTE",
    "TRAVEL_POLE_HIDE_QTE",
    "TRAVEL_POLE_UPDATE_QTE_COUNTDOWN",
    "TRAVEL_POLE_TRIGGER_DEFAULT_NEXT",
    "TRAVEL_POLE_TRIGGER_CLOSE_PANEL",
    "ON_BUILD_POWER_POLE_TRAVEL_HINT",
    "ON_MOVE_POWER_POLE_TRAVEL_HINT",

    
    "ON_SYNC_ALL_MISSION",
    "REFRESH_MISSION_TRACK_ALPHA",
    "ON_TRACK_MISSION_CHANGE",
    "ON_MISSION_STATE_CHANGE",
    "ON_QUEST_STATE_CHANGE",
    "ON_BLOCK_QUEST_STATE_CHANGE",
    "ON_QUEST_OBJECTIVE_UPDATE",
    "ON_COMPLETE_MISSION",
    "SHOW_MISSION_TRACKER",
    "SHOW_MISSION_END_GAME_PANEL",
    "ON_MISSION_DELETED",
    "ON_QUEST_DELETED",
    "ON_CHAPTER_START",
    "ON_CHAPTER_COMPLETED",
    "ON_SHOW_CHAPTER_PANEL_DIRECT",

    "ON_TRACKING_SNS",
    "ON_TRACKING_TO_UI",
    "ON_HUD_ORDER_ENQUEUE",
    "ON_HUD_COMPLETE_ORDER_ENQUEUE",
    "ON_MISSION_VAR_CHANGE",
    "ON_MISSION_HUD_EXCLUSIVE_MODE_CHANGE",
    "ON_MISSION_HUD_SHOW_OPEN_BTN_CHANGE",

    "ON_COMPLETE_MISSION_ANIM_START",
    "ON_START_MISSION_HUD_ANIM",
    "ON_FINISH_MISSION_HUD_ANIM",

    
    "ON_ENEMY_DAMAGETAKENSCALAR_CHANGED",
    "SHOW_BLOCK_GLITCH_TRANSITION",
    "PREPARE_BLOCK_GLITCH_TRANSITION",
    "OPEN_INT_REPAIR_BUILDING_PANEL",
    "OPEN_INT_POWER_POLE_PANEL",
    "ON_INT_REPAIR_BUILDING_RESULT",
    "SHOW_CHAR_INFO_MODEL",
    "MANUALLY_GOTO_NEXT_STEP",
    "ON_DEBUG_TOGGLE_SKILL_RECOVER_BUTTON",
    "ON_COMBO_SKILL_START",
    "ON_BATTLE_ASSETS_RELOAD",

    "ON_TOGGLE_PHASE_FORBID",

    "ON_COMMON_UNLOCK_RESP",
    "ON_READ_RED_DOT_RESP",

    "ON_TELEPORT_SQUAD",
    "ON_TELEPORT_FINISH",

    "ON_PIN_CRAFT_RESP",
    "ON_PIN_BUILDING_RESP",
    "ON_CAST_SKILL",

    "DEAD_ZONE_ROLLBACK",
    "ALL_CHARACTER_DEAD",
    "ALL_CHARACTER_REVIVE",
    "ON_REPATRIATE",

    "ON_APPLICATION_FOCUS",
    "ON_APPLICATION_PAUSE",
    "ON_APPLICATION_QUIT",
    "UPDATE_DEBUG_TEXT",
    "ON_GET_MAIN_SP",
    "ON_CLEAR_SKILLBTN_STATE",
    "ON_PRESS_SKILL_BUTTON",
    "ON_RELEASE_SKILL_BUTTON",
    "ON_PRESS_AND_RELEASE_SKILL_BUTTON",
    "ON_DASH_COUNT_MAX_CHANGED",
    "ON_SWITCH_CENTER_BTN_CLICK",

    "REFRESH_DEBUG_PANEL_BTN",
    "GUIDE_SKILL_DATA",
    "ADD_ITEM_SKILL",
    "REMOVE_ITEM_SKILL",
    "ON_ADD_COUNT_DOWN_BAR",
    "ON_REMOVE_COUNT_DOWN_BAR",
    "ON_CHANGE_THROW_MODE",

    "SET_DEBUG_PANEL_BLOCK_INPUT",
    "HIDE_DEBUG_PANEL",

    "ADD_INTERACT_OPTION", 
    
    "UPDATE_INTERACT_OPTION", 
    "REMOVE_INTERACT_OPTION", 
    "ON_INTERACT_FACTORY_UI_OPTION",
    "TOGGLE_HIDE_INTERACT_OPTION_LIST",

    "ADD_INTERACT_OPTIONS",
    "UPDATE_INTERACT_OPTIONS",
    "REMOVE_INTERACT_OPTIONS",

    "ON_USE_ITEM_SLOT_CHANGED",
    "ON_CHOOSE_CUR_USE_ITEM",
    "ON_TOGGLE_ITEM_SLOT_DROP_HIGHLIGHT",
    "RESET_DROP_HIGHLIGHT",

    "SHOW_SUBMIT_PANEL",
    "SHOW_SUBMIT_INTERACTIVE_PANEL",
    "ON_SUBMIT_ITEM",

    "EXIT_ALL_PHASE",
    "ON_DO_CLOSE_MAP",

    "FAC_ON_COMPLETE_NEW_MANUAL_CRAFT",
    "FAC_ON_CANCEL_MANUAL_CRAFT",

    "SHOW_REPAIR_INTERACTIVE",
    "SHOW_REPAIR_INTERACTIVE_BY_MINIGAME",
    "FORCE_CLOSE_REPAIR_INTERACTIVE",

    "ON_SUBMIT_ETHER_SUCC",
    "SHOW_SUBMIT_ETHER",
    "SHOW_CHARACTER_SUMMON",
    "SHOW_SPACESHIP_VISITOR",
    "SHOW_SPACESHIP_CLUE_SCHEDULE",
    "SHOW_SPACESHIP_CLUE_SETTLEMENT",
    "SHOW_SPACESHIP_CLUE_GIFT",

    "ON_SYNC_INVENTORY",
    "ON_USE_ITEM",
    "ON_ITEM_LOCKED_STATE_CHANGED",
    "ON_ITEM_TRASH_STATE_CHANGED",
    "ON_ITEM_FLAG_CHANGED",
    "ON_ITEM_BAG_LIMIT_CHANGED",
    "ON_ITEM_BAG_CHANGED",
    "ON_FACTORY_DEPOT_CHANGED",
    "ON_VALUABLE_DEPOT_CHANGED",
    "ON_VALUABLE_DEPOT_IMPORT_ITEM_CHANGED",
    "ON_EQUIP_DEPOT_CHANGED",
    "ON_ITEM_COUNT_CHANGED", 
    "ON_ITEM_COUNT_CHANGED_FOR_TOAST",
    "ON_GET_IMPORTANT_REWARD_ITEM",
    "ON_ITEM_TRY_TO_SWITCH_DEAD_CHARACTER", 
    "ON_EQUIP_RECYCLE",
    "ON_LT_ITEM_EXPIRE",
    "ON_LT_ITEM_EXPIRE_CONFIRM_RSP",
    "ON_BATTLE_PASS_TICKET_REWARD",

    "ON_FACTORY_DEPOT_MOVE_TO_ITEM_BAG_BY_INDEX", 
    "ON_FACTORY_DEPOT_MOVE_TO_ITEM_BAG_BY_MODE", 
    "ON_ITEM_BAG_MOVE_TO_FACTORY_DEPOT", 

    "ON_FAC_MOVE_ITEM_CACHE_TO_BAG", 
    "ON_FAC_MOVE_ITEM_GRID_BOX_TO_BAG", 
    "ON_FAC_MOVE_ALL_CACHE_OUT_ITEM_TO_BAG", 

    "ON_FAC_MOVE_ITEM_CACHE_TO_DEPOT", 
    "ON_FAC_MOVE_ITEM_GRID_BOX_TO_DEPOT", 

    "ON_FAC_MOVE_ITEM_BAG_TO_CACHE", 
    "ON_FAC_MOVE_ITEM_DEPOT_TO_CACHE", 

    "ON_FAC_MOVE_ITEM_BAG_TO_GRID_BOX", 
    "ON_FAC_MOVE_ITEM_DEPOT_TO_GRID_BOX", 

    "ON_SYNC_WALLET",
    "ON_WALLET_CHANGED",
    "SHOW_WALLET_BAR",
    "HIDE_WALLET_BAR",
    "HIDE_WALLET_BAR_FORCE",
    "SHOW_WALLET_BAR_FORCE",
    "PLAY_WALLET_BAR_OUT_ANIM",

    "ON_STAMINA_CHANGED",

    "ON_RECOVER_AP_BY_MONEY_COUNT_RESTORED", 

    "ON_MAINCHAR_ENTER_MUD",
    "ON_MAINCHAR_LEAVE_MUD",

    "ENTER_LEVEL_HALF_SCREEN_PANEL_MODE",
    "EXIT_LEVEL_HALF_SCREEN_PANEL_MODE",

    "SET_PHASE_LEVEL_TRANSITION_RESERVE_PANELS",
    "ON_PHASE_LEVEL_DESTROYED",

    "ON_GET_MAIL",
    "ON_ALL_MAIL_INITED",
    "ON_READ_MAIL",
    "ON_GET_MAIL_ATTACHMENT",
    "ON_DEL_MAILS",
    "ON_GET_NEW_MAILS",
    "ON_MARK_STAR_MAIL",

    "ON_GET_LOST_AND_FOUND",
    "MAP_POINT_TRACK_DISTANCE_INFO",
    "ON_ADD_LOST_AND_FOUND",
    "ON_LOST_AND_FOUND_NOTHING_GET",
    "ON_MARQUEE_START",
    "ON_MARQUEE_STOP",

    "ON_ENV_TALK_CHANGED",
    "ON_DIALOG_ENV_TALK_CHANGED",
    "ON_HEAD_LABEL_STATE_CHANGED",
    "ON_HEAD_LABEL_GIFT_CHANGED",

    "ON_OPEN_PRTS_READING_PANEL",

    "ON_ULTIMATE_SKILL_START",
    "ON_ULTIMATE_SKILL_END",
    "ON_COMBO_SKILL_READY",
    "ON_COMBO_SKILL_REMOVE",
    "ON_COMBO_SKILL_CLEAR_ALL",

    "ON_OPEN_INIT_PANELS",

    "ON_TOGGLE_FAC_TOP_VIEW",
    "ON_FAC_TOP_VIEW_CAM_TARGET_MOVED",

    "FAC_TOP_VIEW_SET_BLUEPRINT_ICONS",
    "FAC_TOP_VIEW_SET_BLUEPRINT_ICON_POS",

    "FAC_ON_ADD_NEW_VISIBLE_FORMULA",
    "ON_FOUND_ITEM",
    "ON_READ_FORMULA",
    "ON_ADD_NEW_UNREAD_FORMULA",

    "SHOW_ITEM_SELECT_PANEL",
    "HIDE_ITEM_SELECT_PANEL",

    "SHOW_BOX_GAME_PANEL",
    "HIDE_BOX_GAME_PANEL",

    "ON_ANCHOR_WAVE_ORIGINIUM_SLUG_HIT_BY_PLAYER",

    
    "ON_MANUAL_WORK_MODIFY",
    "ON_GET_NEW_MANUAL_FORMULA",
    "ON_MANUAL_WORK_CANCEL",
    "ON_READ_MANUAL_CRAFT",
    "ON_UNREAD_MANUAL_CRAFT",
    "ON_UNREAD_MANUAL_CRAFT_REWARD",
    "ON_READ_MANUAL_CRAFT_REWARD",
    "ON_MANUAL_CRAFT_GET_ITEM_REWARD",
    "ON_MANUAL_CRAFT_ITEM_LEVEL_UP",
    "ON_MANUAL_CRAFT_LEVEL_UP",

    "ON_GET_MANUAL_REWARD",
    "ON_UNLOCK_MANUAL_CRAFT",

    

    
    "ON_ENTITY_ALL_CPT_START_DONE",
    

    
    "ON_MANUFACT_SETTLES",
    "ON_MANUFACT_START",
    

    
    "ON_REMOTE_FACTORY_ENTITY_ADDED", 
    "ON_REMOTE_FACTORY_ENTITY_REMOVED",
    "FAC_ON_NODE_ADDED", 
    "FAC_ON_NODE_REMOVED",
    "FAC_ON_FLUID_IN_BUILDING_REMOVED",
    "FAC_ON_BUILDING_MOVED",
    "FAC_ON_BUILDING_BATCH_MOVED",

    "ON_ENTER_FAC_MAIN_REGION",
    "ON_EXIT_FAC_MAIN_REGION",

    "ON_FAC_TRANS_ROUTE_CHANGE",

    "ON_IN_FAC_MAIN_REGION_CHANGE",
    "ON_ENTER_FACTORY_MODE",
    "ON_EXIT_FACTORY_MODE",
    "ON_FAC_MODE_CHANGE",
    "ON_FAC_BUILDING_PREVIEW_POSITION_ROTATION_CHANGED",
    "ON_FAC_CHAPTER_RESET",

    "FAC_ON_BUILDING_REPAIRED",
    

    
    "ON_TRADE_SET_CONTRACT_SUCC",
    "ON_TRADER_MODIFY",
    "ON_TRADE_CASH_ORDER_SUCC",
    

    
    "ON_PROCESSOR_MAKE_SUCC",
    "ON_PROCESSOR_MODIFY",
    "ON_PROCESSOR_GET_ITEMS",
    

    
    "SHOW_RADIO",
    "MANUAL_STOP_RADIO",
    "FLUSH_RADIO",
    "ENABLE_RADIO_QUEUE_LOG",
    "ON_RADIO_FINISH",

    "ON_RADIO_EMPTY_SHOW",
    "ON_RADIO_EMPTY_HIDE",
    "ON_RADIO_ONLY_SOUND_CHANGED",
    "ON_FORCE_PLAY_RADIO_CHANGED",
    

    
    "SHOW_REMOTE_COMM",
    "ON_SYNC_ALL_BIT_SET_REMOTE_COMM",
    "ON_ADD_BIT_SET_REMOTE_COMM",
    "REMOTE_COMM_START",
    "REMOTE_COMM_SKIP_END",
    "REMOTE_COMM_NEXT",
    "REMOTE_COMM_PAUSE",
    "REMOTE_COMM_RESUME",
    

    
    "ON_FACTORY_CHARACTER_MODIFY",
    "ON_FACTORY_SKILL_BOARD_MODIFY",
    

    
    "ON_SYNC_POWER_DATA",
    "ON_SYNC_PRODUCT_DATA",
    "ON_SYNC_BOOKMARK_ITEM",
    

    
    "ON_CHAR_INFO_TALENT_SKILL_NEXT_EXPAND",
    "ON_CHAR_INFO_TALENT_INIT_CONTROLLER",
    "SHOW_CHAR_SKILL_TIP",
    "ON_CHAR_SHOW_TALENT_TIPS",
    "ON_CHAR_SHOW_FAC_SKILL_TIPS",

    "WEAPON_EXHIBIT_SELECT_WEAPON_CHANGE",
    "WEAPON_EXHIBIT_PAGE_CHANGE",
    "WEAPON_EXHIBIT_TOGGLE_GEM_LIST",
    "WEAPON_EXHIBIT_REFRESH_GEM_CARD",

    "ON_WEAPON_GAIN_EXP",
    "ON_WEAPON_BREAKTHROUGH",
    "ON_GEM_ATTACH",
    "ON_GEM_DETACH",

    "ON_GEM_RECAST",
    "DEBUG_CHAR_INFO_SHOW_CHAR_SP",

    "CHAR_INFO_SHOW_FC_ATTR_HINT",
    "CHAR_INFO_SHOW_SC_ATTR_HINT",

    "ON_PUT_ON_EQUIP",
    "ON_PUT_OFF_EQUIP",
    "ON_SELECT_SLOT_CHANGE",
    "ON_CHAR_LEVEL_UP",
    "ON_CHAR_GAIN_EXP",
    "SHOW_LEVEL_UP_POPUP",
    "SHOW_BREAK_POPUP",
    "ON_SKILL_UPGRADE_SUCCESS",
    "SHOW_SKILL_UPGRADE_POPUP",
    "ON_CLOSE_SKILL_UPGRADE_POPUP",

    "ON_TALENT_UPGRADE_SUCCESS",
    "ON_UNLOCK_SKILL",
    "ON_PUT_ON_WEAPON",
    "ON_CHAR_TEAM_MEMBER_COUNT_CHANGED",
    "ON_CHAR_INFO_UPGRADE_REFRESH_GOLD",
    "ON_CHAR_INFO_SELECT_EQUIP_CHANGE",
    "ON_CHAR_INFO_SELECT_TACTICAL_CHANGE",
    "ON_CHAR_INFO_EQUIP_TOGGLE_COMPARE_MASK",
    "TOGGLE_CHAR_INFO_FOCUS_MODE",
    "TRY_CLOSE_CHAR_TALENT",
    "CHAR_INFO_CANCEL_TALENT_SELECT",
    "CHAR_INFO_TALENT_REMOTE_EXCHANGE_TO_SKILL",
    "CHAR_INFO_TALENT_EXIT_EXPAND_NODE",
    "TOGGLE_CHAR_INFO_TOGGLE_MENU_AND_TOP_BTN",
    "CHAR_INFO_CLOSE_SKILL_TIP",
    "ON_CHAR_INFO_SHOW_SKILL_TIP",
    "ON_CHAR_INFO_CLOSE_SKILL_TIP",
    "CHAR_INFO_CLOSE_ATTR_TIP",
    "ON_CHAR_INFO_SHOW_ATTR_TIP",
    "ON_CHAR_INFO_CLOSE_ATTR_TIP",
    "CHAR_INFO_SHOW_FULL_ATTRIBUTE",
    "CHAR_INFO_SHOW_FRIENDSHIP_TIPS",

    "ON_CHAR_INFO_UPGRADE_PREVIEW_LEVEL",
    "CHAR_TALENT_SHOW_SKILL",
    "CHAR_TALENT_SHOW_PASSIVE_SKILL",
    "CHAR_TALENT_SHOW_ATTRIBUTE",
    "CHAR_TALENT_SHOW_SHIP_SKILL",
    "CHAR_TALENT_SHOW_CHAR_BREAK",
    "CHAR_TALENT_SHOW_EQUIP_BREAK",
    "CHAR_TALENT_FOCUS",
    "CHAR_TALENT_LEAVE_FOCUS",
    "ON_CHAR_TALENT_UPGRADE",
    "ON_WEAPON_REFINE",
    "CLOSE_WEAPON_EXHIBIT_GEM_CARD",
    "CHAR_INFO_CLOSE_INFO_TIP",
    "CHAR_INFO_SELECT_CHAR_CHANGE",
    "CHAR_INFO_PAGE_CHANGE",
    "CHAR_INFO_SELECT_EQUIP_SLOT_CHANGE",
    "CHAR_INFO_EMPTY_BUTTON_CLICK",
    "CHAR_INFO_BLEND_EXIT",
    "CHAR_INFO_PROFILE_CLOSE",
    "CHAR_INFO_EQUIP_SECOND_OPEN",
    "CHAR_INFO_EQUIP_SECOND_CLOSE",
    "CHAR_INFO_WEAPON_SECOND_OPEN",
    "CHAR_INFO_WEAPON_SECOND_CLOSE",
    "CHAR_INFO_SHOW_ROTATE_CHAR",
    "CHAR_INFO_SHOW_ZOOMING",
    "CHAR_INFO_PREVIEW_WEAPON",
    "WEAPON_EXHIBIT_BLEND_EXIT",
    "CHAR_INFO_WEAPON_SELECT_WEAPON",
    

    
    "ON_CHAR_FORMATION_ENTER_MULTI_SELECT",
    "ON_CHAR_FORMATION_LIST_CONFIRM",
    "ON_CHAR_FORMATION_TEAM_SET",
    "ON_CHAR_FORMATION_SELECT_TEAM_CHANGE",
    "ON_CHAR_FORMATION_LIST_MULTI_SELECT",
    "ON_CHAR_FORMATION_LIST_SINGLE_SELECT",
    "ON_CHAR_FORMATION_CONFIRM_SINGLE_CHAR",
    "ON_CHAR_FORMATION_UNEQUIP_INDEX",
    "ON_CHAR_FORMATION_REFRESH_SLOT",
    "ON_CHAR_FORMATION_CHANGE_HOVER_INDEX",
    "ON_CHAR_FORMATION_CONFIRM_HOVER",
    

    "ON_COMMON_BACK_CLICKED",

    
    "SHOW_READING_POP_PANEL",
    "SHOW_READING_POP_PANEL_BY_HANDLE",
    

    
    "GAME_MODE_ENABLE",
    "GAME_MODE_DISABLE",
    

    
    "ON_SUB_GAME_UNLOCK",
    "ON_SUB_GAME_CUSTOM_REWARD_CHANGE",
    

    
    "ON_SYNC_BLOC_MISSION_INFO",
    "ON_ROLL_BLOC_MISSION",
    "ON_BLOC_COMPLETED_MISSION_NUM_UPDATE",
    "ON_ROLL_COUNT_CHANGE",
    

    
    "ON_WIKI_ENTRY_UNLOCKED",
    "ON_WIKI_ENTRY_READ",
    "SHOW_WIKI_ENTRY",
    "WIKI_SELECT_ENTRY",
    "ON_WIKI_SEARCH_KEYWORD_CHANGED",
    "SHOW_WIKI_REF_TIPS",
    "HIDE_WIKI_REF_TIPS",
    "SHOW_WIKI_WEAPON_PREVIEW",
    "CHANGE_WIKI_DEFAULT_CRAFT",
    "CHANGE_WIKI_CRAFTING_TREE",
    

    
    "ON_OPEN_BLACKBOX_ENTRY_PANEL",
    "ON_OPEN_DUNGEON_ENTRY_PANEL",
    "ON_DUNGEON_COMPLETE",
    "ON_START_DUNGEON_CHALLENGE",
    "ON_DUNGEON_CHALLENGE_STATUS_CHANGE",
    "ON_DUNGEON_COUNT_DOWN",
    "TRY_START_SETTLEMENT",
    "ON_SHOW_DUNGEON_RESULT",
    "ON_SHOW_BLACKBOX_RESULT",
    "ON_DUNGEON_SERIES_ACTIVE",

    "ON_DUNGEON_WARNING_STATE_CHANGE",

    "ON_BLACKBOX_READ",
    "ON_BLACKBOX_ACTIVE",
    "ON_DUNGEON_GAME_INIT",
    "ON_DUNGEON_GAME_START",
    "ON_ENTER_DUNGEON", 
    "ON_LEAVE_DUNGEON",
    "ON_DUNGEON_RESTART",
    "ON_DUNGEON_SETTLEMENT_CLOSED",
    "ON_DUNGEON_SETTLEMENT_OPENED",
    "SHOW_ENTER_PRESET_TEAM_DUNGEON_CONFIRM",

    
    "ON_CHAR_TUTORIAL_STEP_STATE_CHANGE",
    "OPEN_CHAR_TUTORIAL_STEP_HUD",
    "LEVEL_SCRIPT_PUSH_STAGE",
    "TOGGLE_CHAR_TUTORIAL_STEP_HUD",
    

    
    "ON_UNLOCK_PRTS",
    "ON_UNLOCK_PRTS_FIRST_LV",
    "ON_PRTS_TERMINAL_READ",
    "ON_READ_PRTS",
    "ON_UNREAD_PRTS",
    "ON_READ_PRTS_NOTE_BATCH",
    "ON_UNREAD_PRTS_NOTE_BATCH",
    
    "PRTS_CHANGE_INVESTIGATE_GALLERY_NOTE_VISIBLE",
    "ON_INVESTIGATE_FINISHED",
    "SHOW_PRTS_STORY_COLL_DETAIL",
    "SHOW_PRTS_INVEST_DETAIL",
    "ON_UNLOCK_PRTS_NOTE_BATCH",
    

    
    "ON_LOGIN_CLICK_SETTING_BTN",
    "ENTER_GAME_CLICKED",
    "ON_QUICK_LOGIN",
    "ON_FIRST_LOGIN",
    "ON_OPEN_LEADING_CHARACTER",
    "LOGIN_SELECT_GENDER",
    "ON_SYNC_BASE_DATA",
    "ON_REQUEST_EXIT_GAME",
    "ON_REQUEST_RELOGIN",
    "ON_FAKE_ACCOUNT_CENTER",
    "ON_GENDER_HOVER_CHANGE",
    "ON_GENDER_HOVER_ANIM",
    

    
    

    
    "ON_PIN_STATE_CHANGED",
    


    
    "SHOW_CONTROLLER_HINT",
    "HIDE_CONTROLLER_HINT",
    "REFRESH_CONTROLLER_HINT",
    "REFRESH_CONTROLLER_HINT_CONTENT_IMMEDIATELY",
    "REFRESH_CONTROLLER_HINT_ORDER",
    "PLAY_CONTROLLER_HINT_OUT_ANIM",

    "SHOW_CONTROLLER_NAVI_TEXT_HINT",
    "HIDE_CONTROLLER_NAVI_TEXT_HINT",
    "HYPERLINK_UITEXT_GROUP_DISPLAYABLE_CHANGE",
    "TOGGLE_CONTROLLER_HINT",
    

    "REFRESH_CHAR_CONTROLLER_HINT",
    "REFRESH_CHAR_EMPTY_SORTING_ORDER",

    "SHOW_DEBUG_PHASE",
    "HIDE_DEBUG_PHASE",
    "UPDATE_DEBUG_PHASE_TEXT",

    "SHOW_DEBUG_BLUR",
    "ADD_UI_BLUR",
    "ADD_UI_BLUR_RANDOM",

    
    "ON_ENTER_RPG_DUNGEON",
    "ON_LEAVE_RPG_DUNGEON",
    "ON_TEAM_EXP_CHANGE",
    "ON_TEAM_LEVEL_UP",
    "ON_FINISH_PICK_ABILITY",
    "ON_RPG_EQUIP_COLUMN_CHANGE",
    "OPEN_RPG_DUNGEON_SHOP",
    "ON_BUY_RPG_DUNGEON_EQUIP_SUCC",
    "ON_PUT_ON_RPG_DUNGEON_EQUIP_SUCC",
    "ON_PUT_OFF_RPG_DUNGEON_EQUIP_SUCC",
    "ON_SELL_RPG_DUNGEON_EQUIP_SUCC",
    "ON_START_RPG_DUNGEON_COUNTDOWN",
    

    
    "PLAY_CG",
    "PRELOAD_FMV_IN_CINEMATIC",
    "RELEASE_PRELOADED_FMV",
    "PLAY_FMV_SYNC_IN_CINEMATIC",
    "STOP_FMV_IN_CINEMATIC",
    "ON_NARRATIVE_STATE_CHANGED",

    "ON_SYNC_ALL_BIT_SET_FMV",
    "ON_ADD_BIT_SET_FMV",
    "SKIP_FMV",
    "ON_SHOW_BIG_LOGO_FMV",

    "ON_PLAY_CUTSCENE",
    "ON_FINISH_CUTSCENE",
    "ON_LOAD_NEW_CUTSCENE",
    "ON_LOAD_NEW_DLG_TIMELINE",
    "ON_SYNC_ALL_BIT_SET_CUTSCENE",
    "ON_ADD_BIT_SET_CUTSCENE",
    "ADD_CINEMATIC_ITEM_TO_QUEUE",
    "END_CINEMATIC_QUEUE_ITEM",
    "TOGGLE_IGNORE_CINEMATIC_QUEUE",

    "CHAR_INTERACT_PERFORM_EXIT",
    "CHAR_INTERACT_PERFORM_STATE_CHANGED",

    "SHOW_SKETCH_PANEL",
    "ON_SHOW_BIG_LOGO",
    "ON_PREPROCESS_TIMELINE_ACTORS",
    "ON_DETACHED_TIMELINE_ACTORS",

    "ON_CINEMATIC_TO_QUEUE",

    
    "ON_DIALOG_START",
    "UI_DIALOG_TEXT_STOPPED",
    "ON_DIALOG_DISABLE_CLICK_END",
    "SWITCH_DIALOG_CAN_SKIP",
    "SWITCH_DIALOG_SHOW_LOG",
    "ON_EXIT_DIALOG",
    "ON_FINISH_DIALOG",
    "ON_SYNC_ALL_DIALOG",
    "DIALOG_OPEN_UI",
    "DIALOG_CLOSE_UI",
    "ON_PLAY_DIALOG_TRUNK",
    "ON_PLAY_DIALOG_TIMELINE",
    "ON_FINISH_DIALOG_TIMELINE",
    "ON_DIALOG_TIMELINE_START_TRUNK",
    "ON_DIALOG_TIMELINE_STOP_TRUNK",
    "ON_DIALOG_TIMELINE_START_LEFT_SUBTITLE",
    "ON_SHOW_DIALOG_OPTION",
    "ON_SHOW_DIALOG_TIMELINE_OPTION",
    "ON_DIALOG_TRUNK_TEXT_FADE",
    "ON_DIALOG_TRUNK_RADIO_FADE",
    "ON_DIALOG_CHANGE_CENTER_IMAGE",
    "DIALOG_PANEL_SHOW_FULL_BG",
    "DIALOG_PANEL_SHOW_POST_PROCESS_EFFECT",
    "DIALOG_PANEL_SHOW_LEFT_SUBTITLE",
    "DIALOG_PANEL_EXIT_LEFT_SUBTITLE",
    "DIALOG_SEND_PRESENT_END",
    "DIALOG_REFRESH_AUTO_MODE",
    "DIALOG_TIMELINE_REFRESH_AUTO_MODE",
    "DIALOG_SHOW_DEV_WATER_MARK",
    "ON_BLACK_SCREEN_IN",
    "ON_BLACK_SCREEN_OUT",

    "NOTIFY_MAIN_HUD_BLACK_SCREEN_END",
    "NOTIFY_MAIN_HUD_BLACK_SCREEN_BEGIN",

    "REFRESH_DIALOG_TIMELINE_CAN_CLICK",
    "OPEN_DIALOG_RECORD",
    "OPEN_DIALOG_TIMELINE_RECORD",

    "HIDE_DIALOG_RECORD",

    "ON_START_CAMERA_CROSS_FADE",
    "ON_STOP_CAMERA_CROSS_FADE",

    "SKIP_DIALOG",
    "SKIP_DIALOG_TIMELINE",

    "OPEN_DIALOG_SKIP_POP_UP",
    "OPEN_DIALOG_TIMELINE_SKIP_POP_UP",

    "HIDE_DIALOG_SKIP_POP_UP",
    "HIDE_DIALOG_TIMELINE_SKIP_POP_UP",

    "ON_PRELOAD_DIALOG_PANEL",
    "ON_PRELOAD_DIALOG_TIMELINE_PANEL",
    

    "SHOW_SORT_POP_OUT",

    

    
    "ON_GET_SNS_CHAT_LIST",
    "ON_SNS_DIALOG_MODIFY",
    "ON_SNS_DIALOG_SET_OPTION",
    "ON_SNS_NORMAL_DIALOG_ADD",
    "ON_SNS_FRIEND_CHAT_ADD",
    "ON_SNS_FORCE_DIALOG_ADD",
    "ON_SNS_FORCE_DIALOG_PANEL_OPEN",
    "ON_SNS_FORCE_DIALOG_START",
    "ON_SNS_FORCE_DIALOG_END",
    "ON_SNS_MOMENT_ADD",
    "ON_READ_SNS_DIALOG",
    "ON_READ_SNS_MOMENT",
    "ON_SHOW_SNS_NEW_DIALOG_TOAST",
    "INTERRUPT_FORCE_SNS",
    "ON_SNS_DIALOG_CONTENT_LOADING_FINISH",
    "ON_SNS_CONTENT_CORE_CELL_SIZE_CHANGED",
    "ON_SNS_BARKER_TAB_READ_STATE_CHANGE",
    "ON_SNS_MISSION_TAB_READ_STATE_CHANGE",
    

    
    "ON_ONE_COMMON_TASK_PANEL_FINISH",
    
    
    "ON_ONE_COMMON_TASK_REQUEST_FINISH",
    "INTERRUPT_COMMON_TASK_PANEL",
    "ON_SHOW_COMMON_TASK_COUNTDOWN_TOAST",
    "ON_SHOW_COMMON_TASK_COUNTDOWN",
    "ON_CLOSE_COMMON_TASK_COUNTDOWN",
    "ON_START_COMMON_TASK_COUNTING",
    "ON_FINISH_COMMON_TASK_COUNTING",
    "ON_SHOW_COMMON_TASK_TOAST_START",
    "ON_SHOW_COMMON_TASK_TOAST_FINISH",
    "ON_SHOW_COMMON_TASK_TOAST_FAIL",
    "ON_OPEN_SUB_GAME_TRACKINGS",
    "ON_CLOSE_SUB_GAME_TRACKINGS",
    "ON_DEACTIVATE_COMMON_TASK_TRACK_HUD",
    "ON_OPEN_SCRIPT_CUSTOM_TASK_TRACKING",
    "ON_CLOSE_SCRIPT_CUSTOM_TASK_TRACKING",
    "ON_HUD_BTN_VISIBLE_CHANGE",
    "ON_SUB_GAME_RESET",
    "ON_SUB_GAME_QUIT",
    "ON_SCRIPT_TASK_CHANGE",
    "ON_SUB_GAME_FINISH_STATE_CHANGE",
    "ON_TASK_OBJECTIVE_PROGRESS_CHANGE",
    "ON_SUB_GAME_STAGE_CHANGE",
    "ON_SUB_GAME_STAGE_CHANGE_FINISH",
    

    "ON_SC_OPEN_USABLE_ITEM_CHEST",
    "ON_SC_ITEM_BAG_USE_ITEM_GEMLOCKEDTERMBOX",
    "ON_GEMCUSTOMIZATIONBOX_TERM_SELECT",

    
    "ON_ADD_RECYCLE_BIN",
    "ON_REMOVE_RECYCLE_BIN",
    "ON_UPDATE_RECYCLE_BIN",
    "ON_ADD_DOODAD_MINE_CORE",
    "ON_REMOVE_DOODAD_MINE_CORE",
    "ON_UPDATE_DOODAD_MINE_CORE",
    "ON_ADD_DOODAD_PLANT_CORE",
    "ON_REMOVE_DOODAD_PLANT_CORE",
    "ON_UPDATE_DOODAD_PLANT_CORE",
    "ON_REFRESH_DOODAD_PLANT_CORE",
    "ON_ADD_LIQUID_POOL",
    "ON_REMOVE_LIQUID_POOL",
    "ON_ADD_SMALL_ENERGY_POINT_UI",
    "ON_REMOVE_SMALL_ENERGY_POINT_UI",
    

    
    "ON_CROP_STEP_CHANGE",
    "ON_OPEN_CROP",
    "ON_CROP_OPERATION_FAILED",
    "ON_CROP_OPERATION_FAILED_FORCE_CLOSE",
    "ON_CROP_EXTRA_OPERATION_FINISH",
    "ON_OPEN_FERTILIZATION",
    "On_FERTILIZE_PANEL_DO_OPERATION",
    

    
    "ON_SETTLEMENT_UNLOCK",
    "ON_SETTLEMENT_UPGRADE",
    "SHOW_SETTLEMENT_UNLOCK_TOAST",
    "SHOW_SETTLEMENT_UPGRADE_TOAST",
    "ON_SETTLEMENT_MODIFY",
    "ON_SETTLEMENT_OFFICER_CHANGE",
    "ON_SETTLEMENT_REMAIN_MONEY_MODIFY",
    "ON_SETTLEMENT_SYNC_ALL",
    "ON_SETTLEMENT_TRADE_SUCCESS",
    

    
    "SHOW_TOWER_DEFENSE_TERMINAL_PANEL",

    "ON_TOWER_DEFENSE_LEVEL_UNLOCKED",
    "ON_ENTER_TOWER_DEFENSE_PREPARING_PHASE",
    "ON_LEAVE_TOWER_DEFENSE_PREPARING_PHASE",
    "ON_ENTER_TOWER_DEFENSE_DEFENDING_PHASE",
    "ON_LEAVE_TOWER_DEFENSE_DEFENDING_PHASE",
    "ON_TOWER_DEFENSE_LEVEL_FINISHED",
    "ON_TOWER_DEFENSE_LEVEL_COMPLETED",
    "ON_TOWER_DEFENSE_LEVEL_HUD_CLEARED",
    "ON_TOWER_DEFENSE_LEVEL_REWARDS_FINISHED",

    "ON_TOWER_DEFENSE_DEFENDING_BATTLE_BUILDING_ADDED",
    "ON_TOWER_DEFENSE_DEFENDING_BATTLE_BUILDING_REMOVED",

    "ON_TOWER_DEFENSE_DEFENDING_READY",
    "ON_TOWER_DEFENSE_TRANSIT_FINISHED",
    "ON_TOWER_DEFENSE_DEFENDING_ENEMY_KILLED",
    

    "ADD_COMMON_WORLD_UI",
    "REMOVE_COMMON_WORLD_UI",

    "SHOW_COMMON_HOVER_TIP",
    "HIDE_COMMON_HOVER_TIP",

    "SHOW_BOMB_AIM",
    "HIDE_BOMB_AIM",
    "ON_SYNC_AIM_POS",
    "SHOW_WATER_DRONE_AIM",
    "HIDE_WATER_DRONE_AIM",
    "SYNC_WATER_DRONE_AIM",
    "SYNC_LIQUID_STATE",
    "SYNC_REMAINING_LIQUID_CAPACITY",
    "SYNC_SPRAYING",
    "SHOW_WATER_DRONE_BAG",
    "HIDE_WATER_DRONE_BAG",
    "WATER_DRONE_AIM_HAS_LIQUID_STATE",
    "WATER_DRONE_LIQUID_STATE_EMPTY",
    "SYNC_WATER_DRONE_SHOOT_BUT_BANNED_HINT_LIQUID",

    
    "ON_SHOP_REFRESH",
    "SHOP_GROUP_CONDITION_SYNC",
    "ON_SHOP_MONEY_EXCHANGE_SUCC",
    "ON_SHOP_JUMP_EVENT",
    "ON_SHOP_FREQUENCY_LIMIT_CHANGE",
    "ON_SHOP_GOODS_LOCK_CHANGE",
    "ON_SHOP_GOODS_CONDITION_REFRESH",
    "ON_SHOP_GOODS_SEE_GOODS_INFO_CHANGE",
    "SHOP_ITEM_SOLD_OUT_ANIMATION_END",
    "SHOP_WAIT_ANIMATION",
    "SHOW_SHOP_ITEM_POP_UP",
    "ON_BUY_ITEM_SUCC",
    "ON_SELL_ITEM_SUCC",
    
    "ON_FRIEND_GOODS_INFO_SYNC",
    "ON_FRIEND_SHOP_INFO_SYNC",
    "ON_SHOP_GOODS_MANUAL_REFRESH",
    "ON_DOMAIN_SHOP_CHANNEL_UNLOCK",
    "ON_DOMAIN_SHOP_CHANNEL_LEVEL_UP",
    "OPEN_DOMAIN_FRIEND_SHOP",
    "OPEN_DOMAIN_SHOP",
    

    
    "ON_MONTHLY_PASS_DAILY_GET_REWARD",
    "ON_SYNC_MONTHLY_CARD_DATA",
    

    
    "ON_CASH_SHOP_REFRESH",
    "CASH_SHOP_SHOW_WALLET_BAR",
    "ON_CASH_SHOP_ORDER_SETTLE",
    "ON_SDK_PRODUCT_INFO_UPDATE",
    "ON_CASH_SHOP_PLATFORM_DATA_REFRESH",
    "CASH_SHOP_NEW_OPEN_GOODS",
    "ON_SC_SHOP_SWAP_CHAR_POTENTIAL_UP",
    "ON_ACCEPT_ORDERS",
    "ON_READ_CASH_SHOP_GOODS",
    "ON_CLOSE_SHOP_DETAIL_PANEL",
    "ON_PAY_ERROR",
    "ON_CASH_SHOP_PACK_SET_TOP",
    "CASH_SHOP_CHOOSE_GIFTPACK_TAB_BY_GOODSID",
    "ON_CASH_SHOP_OPEN_CATEGORY",
    "CASH_SHOP_REFRESH_CLOSE_BTN_UI",
    "ON_SHOP_SHOW_REWARD",
    "ON_OPEN_CASH_SHOP_DETAILS",
    "ON_CLOSE_CASH_SHOP_DETAILS",
    

    "SHOW_COMMON_PICTURE",
    "SHOW_COMMON_VIDEO",

    "CURRENT_LEVEL_CHANGE",

    "ON_TELEPORT_TO",

    
    "ON_EQUIP_TECH_UNLOCK",
    "ON_EQUIP_PRODUCE",
    "ON_EQUIP_ENHANCE",
    "ON_EQUIP_FORMULA_UNREAD",
    "ON_EQUIP_FORMULA_READ",
    "ON_NEW_VERSION_EQUIP_FORMULA_READ",
    "ON_NEW_VERSION_EQUIP_FORMULA_UNREAD",
    "SHOW_REWARD_EQUIP_FORMULA",
    

    
    "ON_CHAR_POTENTIAL_UNLOCK",
    "ON_CHAR_POTENTIAL_PICTURE_READ",
    "ON_CHAR_POTENTIAL_PICTURE_UNREAD",
    "ON_CHAR_SET_POTENTIAL_CG",
    

    
    "ON_ADVENTURE_SYNC_ALL_FINISH",
    "ON_ADVENTURE_EXP_CHANGE",
    "ON_ADVENTURE_EXP_CHANGE_FOR_TOAST",
    "ON_ADVENTURE_REWARD_RECEIVE",
    "ON_ADVENTURE_TASK_MODIFY",
    "ON_ADVENTURE_BOOK_STAGE_MODIFY",
    "ON_CHANGE_ADVENTURE_BOOK_TAB",
    "ON_CHANGE_ADVENTURE_DUNGEON_TAB",
    "ON_ADVENTURE_BOOK_SWITCH_SAME_TAB",
    "P_ON_ADVENTURE_DAILY_CLOSE_REWARD_TIPS",
    "ON_PHASE_ADVENTURE_BOOK_BEHIND",

    "ON_DAILY_ACTIVATION_MODIFY",
    "ON_DAILY_ACTIVATION_REWARD",
    "ON_RESET_DAILY_ADVENTURE_TASK",

    "ADVENTURE_BOOK_SELECT_TAB",

    "ON_SUB_GAME_READ",
    

    "ON_RACING_DUNGEON_GET_ACHIEVE_REWARD",
    "ON_RACING_DUNGEON_GET_WEEKLY_REWARD",
    "ON_RACING_DUNGEON_TLEMENT",
    "ON_ENTER_RACING_DUNGEON",
    "ON_LEAVE_RACING_DUNGEON",
    "SHOW_RACING_DUNGEON_TOAST",
    "SHOW_RACING_DUNGEON_MAP_TOAST",
    "SHOW_RACING_DUNGEON_ACHIEVEMENT_TOAST",
    "SHOW_RACING_OBTAIN_BUFF",
    "ON_RACING_DUNEGON_PAUSE",

    "COMPONENT_CALL_LUA_UI_ON",
    "COMPONENT_CALL_LUA_UI_OFF",

    "SHOW_CHAR_TACTICAL_ITEM_TIP",

    "MIN_MAP_SHOW",

    "RECV_ADD_LUA_SHOW_MESSAGES",
    "RECV_FRIEND_CHAT_CONTENT",
    "RECV_FRIEND_SEND_CHAT_NOTIFY",
    "FRIEND_CHAT_NOTIFY_BLUEPRINT",
    "FRIEND_CHAT_UPDATE_BLUEPRINT",
    "FRIEND_CHAT_NOTIFY_SOCIAL_BUILDING",
    "FRIEND_CHAT_UPDATE_SOCIAL_BUILDING",
    "ON_FAC_SOCIAL_BUILDING_RECEIVED",
    "ON_FAC_RECEIVED_SOCIAL_BUILDING_DATA_UPDATED",

    "SYNC_FRIEND_CHAT_ALL_INFO",
    "ON_CLICK_OPEN_FRIEND_CHAT",
    "FRIEND_CHAT_SCROLL_LIST_TO_INDEX",
    "FRIEND_CHAT_FOCUS_MESSAGE",
    "FRIEND_CHAT_MSG_READ",
    "FRIEND_CHAT_PLAYER_ADD_LIST_CELL",
    "FRIEND_CHAT_PLAYER_DELETE_LIST_CELL",

    "GENERAL_ABILITY_SYSTEM_CHANGED",
    "TEMP_ABILITY_SYSTEM_CHANGED",
    "GENERAL_ABILITY_SYSTEM_FORCE_SELECT",
    "ON_GENERAL_ABILITY_USE",
    "ON_GENERAL_ABILITY_STATE_CHANGE",
    "TOGGLE_GENERAL_ABILITY_CLICK",
    "TOGGLE_GENERAL_ABILITY_LONG_CLICK",
    "TOGGLE_GENERAL_ABILITY_CLOSE_WHEEL",
    "SET_GENERAL_ABILITY_RELEASE_CLOSE",
    "SWITCH_GENERAL_ABILITY_DEBUG_TYPE",
    "CLEAR_GENERAL_ABILITY_DEBUG_TYPE",
    "GENERAL_ABILITY_CHANGE_KEY_BINDING",

    "SHOW_MAP_REGION_TOAST",

    "SHOW_DEATH_INFO",

    "ON_TRACKING_MAP_MARK",

    "ON_MIST_MAP_UNLOCK",
    "ON_ENTER_TIER_REGION",
    "ON_LEAVE_TIER_REGION",
    "ON_ENTER_TIER_CONTAINER_REGION",
    "ON_LEAVE_TIER_CONTAINER_REGION",

    
    "ON_CHAR_VOICE_READ",
    "ON_CHAR_VOICE_UNREAD",
    "ON_CHAR_VOICE_LOCKED",
    "ON_CHAR_VOICE_UNLOCKED",
    "ON_CHAR_DOC_READ",
    "ON_CHAR_DOC_UNREAD",
    "ON_CHAR_DOC_LOCKED",
    "ON_CHAR_DOC_UNLOCKED",
    

    
    "ON_LEVEL_WORLD_UIS_LOADED",
    "ON_LEVEL_WORLD_UIS_RELEASED",
    


    
    "SHOW_ACTIVITY_PANEL",
    "ON_ACTIVITY_UPDATED",
    "ON_ACTIVITY_CENTER_CLOSE",
    "ON_ACTIVITY_NEW_RED_DOT_SET_FALSE",
    "ON_DUNGEON_RESTORE_AP",
    "ON_ACTIVITY_NAVI_FAILED",
    "ACTIVITY_HIGH_DIFFICULTY_NEW_TASK_SET_FALSE",
    "ACTIVITY_MANUALLY_POP_UP",
    "ON_ACTIVITY_NEW_DAY",
    "ON_WEEKLY_TASK_CHANGE",
    "ON_ACTIVITY_BENEFIT_REFRESH",

    
    "ON_HIGH_DIFFICULTY_NEW_RED_DOT_SET_FALSE",
    

    
    "ON_ACTIVITY_CHECK_IN",
    "ON_CHECK_IN_UPDATED",
    "CHECK_IN_REWARD",
    

    
    "ON_LEVEL_REWARD_UPDATE",
    

    
    "ON_CONDITIONAL_MULTI_STAGE_UPDATE",
    "ON_CONDITIONAL_MULTI_STAGE_PROGRESS_CHANGE",
    "ON_READ_ACTIVITY_CONDITION_STAGE",
    

    
    "ON_ACTIVITY_GAME_ENTRANCE_UNLOCK",
    "ON_READ_GAME_ENTRANCE_SERIES",
    

    

    
    "SHOW_RACE_MODULE_RANK_UI",
    "CLOSE_RACE_MODULE_RANK_UI",
    "UPDATE_RACE_MODULE_RANK",
    

    "ON_NEW_SCENE_GRADE_UNLOCK_CHANGED",
    "ON_READ_LEVEL",
    "ON_WORLD_LEVEL_CHANGED",
    "SHOW_SCENE_GRADE_PANEL",
    "ON_SCENE_GRADE_PANEL_CLOSED",

    "FORBID_SYSTEM_CHANGED",

    "ON_ENEMY_SPAWNER_PREVIEW_ROUTE_CREATED",

    "SHOW_BOTTOM_TOAST",
    "CLOSE_BOTTOM_TOAST",
    "ON_CHECK_SENSITIVE_SUCCESS",

    
    "ON_WEEKRAID_DATA_INIT",
    "ON_ACTION_POINT_UPDATE",
    "ON_CLOSE_WEEKRAID_HUD",
    "ON_WEEK_RAID_SETTLEMENT",
    "ON_WEEK_RAID_BATTLE_PASS_UPDATE", 
    "ON_WEEK_RAID_DANGER_METER_MODIFY", 
    "SHOW_WEEK_RAID_LEAVE_CONFIRM", 
    "ON_WEEKLY_RAID_ENTER", 
    "ON_WEEK_RAID_MISSION_REFRESH", 
    "ON_WEEK_RAID_TECH_MODIFY", 
    "ON_WEEKLY_RAID_QUIT", 
    "ON_INTERACT_WEEK_RAID_ENTRY", 
    "ON_WEEK_RAID_MISSION_PIN_CHANGE",
    

    "CHANGE_WATER_MARK_GRID",

    "ON_GAME_SETTING_CHANGED",
    "GAME_SETTING_VOICE_RESOURCE_STATE_CHANGED", 

    
    "SNAPSHOT_PLAYER_MOVE_MODE",
    "SNAPSHOT_CAMERA_MOVE_MODE",
    "ON_SNAPSHOT_IDENTIFY_SUCCESS",
    "CS_TOGGLE_SNAPSHOT_MODE",
    "ON_SHOW_SNAPSHOT",
    "SNAPSHOT_LISTENER_IDENTIFY_CHANGED",
    "CLOSE_SNAPSHOT",
    "SNAPSHOT_INNER_FORBID_JOYSTICK",
    "SNAPSHOT_INNER_FORBID_PLAYER_MOVE",
    

    "ON_DRAG_SPRINT_BTN",
    "ON_DRAG_WATER_DRONE_JOYSTICK",
    "ON_SYSTEM_DISPLAY_SIZE_CHANGED",

    "SHOW_ITEM_DRAG_HELPER",
    "HIDE_ITEM_DRAG_HELPER",

    "ENDMIN_GENDER_SWITCH_START",
    "ENDMIN_GENDER_SWITCH_FINISH",

    "ON_SWITCH_LANGUAGE",
    "ON_SWITCH_LANGUAGE_ENUM",
    "CLOSE_ALL_UI_FOR_SWITCH_LANGUAGE",
    "FORCE_ENABLE_UI_SCENE_BLUR",
    "QUICK_HIDE_FULL_SCREEN_SCENE_BLUR",

    "TOGGLE_PANEL_USE_BLACK_OUT",

    
    "SHOW_COMMON_POI_UPGRADE_TOAST",
    "ON_COMMON_POI_UNLOCKED",
    "ON_COMMON_POI_LEVEL_UP",
    

    
    "ON_RECYCLE_BIN_COLLECTED",
    "ON_RECYCLE_BIN_CAN_PICK_UP",
    "ON_RECYCLE_BIN_UPGRADE_AND_COLLECTED",
    

    
    "ON_DOMAIN_DEVELOPMENT_LEVEL_REWARD_GET",
    "ON_DOMAIN_DEVELOPMENT_EXP_CHANGE",
    "ON_SYNC_DAILY_SOURCE_MONEY_RECORD",
    "ON_SHOW_DOMAIN_TOAST",
    "ON_DOMAIN_DEVELOPMENT_UNLOCK",
    

    
    "ON_CHANGE_FRIEND_TAB",
    "ON_SEARCH_FRIEND_END",
    "ON_FRIEND_INFO_SYNC",
    "ON_FRIEND_INFO_PSN_SYNC",
    "ON_PSN_FRIEND_INFO_SYNC_ERROR",
    "ON_SEND_MSG_FREQUENCY_ERROR",
    "ON_FRIEND_REQUEST_INFO_SYNC",
    "ON_BLACK_LIST_INFO_SYNC",
    "ON_STRANGER_LIST_INFO_SYNC",
    "ON_FRIEND_CELL_INFO_CHANGE",
    "ON_FRIEND_DELETE",
    "ON_FRIEND_REMAKE_NAME_MODIFY",
    "ON_FRIEND_CHAT_CLEAR_SELECT_INFO",
    "ON_FRIEND_REQUEST_CHANGE",
    "ON_OPEN_VISIT_FRIEND_LIST",
    "ON_OPEN_BUSINESS_CARD_PREVIEW",
    "ON_FRIEND_ADD_NOTIFY",
    "ON_FRIEND_NEW_FRIEND_SEARCH_CONTENT_CHANGE",

    "ON_FRIEND_BUSINESS_INFO_CHANGE",
    "ON_FRIEND_CHAR_QUERY",
    "ON_FRIEND_VISIT_SPACESHIP",

    "ON_BUSINESS_CARD_UNLOCK",
    "ON_BUSINESS_CARD_READ",
    "ON_AVATAR_UNLOCK",
    "ON_AVATAR_READ",
    "ON_AVATAR_FRAME_UNLOCK",
    "ON_AVATAR_FRAME_READ",

    

    "ON_NAVI_INVENTORY_SELECT_FLUID",

    
    "FAC_TECH_TREE_OPEN_PACKAGE_PANEL",
    "FAC_TECH_TREE_OPEN_TREE_PANEL",
    "SHOW_TECH_TREE_POP_UP",
    "HIDE_TECH_TREE_POP_UP",
    "CLOSE_TECH_TREE_POP_UP",
    "FAC_ON_REFRESH_TECH_TREE_NODE_NAME",
    "FAC_ON_REFRESH_TECH_TREE_UI",
    "FAC_ON_UNLOCK_TECH_TREE_UI",
    "FAC_ON_UNLOCK_TECH_TIER_UI",
    "FOCUS_TECH_TREE_NODE",
    "ZOOM_TO_FULL_TECH_TREE",
    "ON_FAC_TECH_POINT_GAINED",
    "ON_UNLOCK_FAC_TECH_PACKAGE",
    "ON_UNHIDDEN_FAC_TECH_PACKAGE",
    "ON_UNHIDDEN_CATEGORY_GUIDE_FINISHED",
    


    
    "SHOW_DRAMATIC_PERFORMANCE_BAG",
    "ON_DRAMATIC_PERFORMANCE_BAG_FINISH",

    "OPEN_DRAMATIC_PERFORMANCE_EMPTY_UI",
    "CLOSE_DRAMATIC_PERFORMANCE_EMPTY_UI",
    

    
    "ON_GEM_DISMANTLE",
    "ON_GEM_ENHANCE",
    "ON_WEAPON_ATTACH_GEM_ENHANCE_MAX",
    

    
    "OPEN_FAC_REGION_UPGRADE_PANEL",
    "ON_FAC_REGION_UPGRADE_DATA_CHANGED",
    

    
    "OPEN_PHASE_COMMON_POI",
    

    
    "ON_SHOW_KITESTATION",
    "ON_KITE_STATION_COLLECTION_REWARD",
    "ON_KITE_STATION_MODIFY",
    "ON_KITE_STATION_WEEKLY_RESET",

    

    
    "ON_DOMAIN_DEPOT_UNLOCKED",
    "ON_DOMAIN_DEPOT_UPGRADED",
    "ON_DOMAIN_DEPOT_DELIVERY_REWARD",
    "ON_OPEN_DOMAIN_DEPOT_TAB",
    "ON_CLOSE_DOMAIN_DEPOT_TAB",
    "ON_CHANGE_DOMAIN_DEPOT_TAB",
    "ON_DOMAIN_DEPOT_DELIVERY_SYNC",
    "ON_OPEN_DOMAIN_DEPOT_PACK_TYPE_SELECT_PANEL",
    "ON_CLOSE_DOMAIN_DEPOT_PACK_TYPE_SELECT_PANEL",
    "ON_OPEN_DOMAIN_DEPOT_PACK_ITEM_SELECT_PANEL",
    "ON_DOMAIN_DEPOT_BACK_TO_PACK_TYPE_SELECT_PANEL",
    "ON_CLOSE_DOMAIN_DEPOT_PACK_ITEM_SELECT_PANEL",
    "ON_OPEN_DOMAIN_DEPOT_PACK_SELL_PANEL",
    "ON_CLOSE_DOMAIN_DEPOT_PACK_SELL_PANEL",
    "ON_OPEN_SHOW_SELL_ANIM_PANEL",
    "ON_CLOSE_DOMAIN_DEPOT_PACK_SETTLE_PANEL",
    "ON_PACK_ITEM_END",
    "ON_SELECT_BUYER_END",
    "ON_COLLECT_DELEGATE_REWARD",
    "ON_PACK_INTEGRITY_CHANGED",
    "ON_START_DOMAIN_DEPOT_DELIVER",
    "ON_FINISH_DOMAIN_DEPOT_DELIVER",
    "ON_DOMAIN_DEPOT_DELIVER_STATE_CHANGED",
    "ON_DOMAIN_DEPOT_PACK_FAILED",
    "ON_DOMAIN_DEPOT_DAILY_REFRESHED",
    "ON_CLEAR_DOMAIN_DEPOT_DELIVERING_INST",
    

    
    "OPEN_FREEZE_WORLD_PANEL",
    "CLOSE_FREEZE_WORLD_PANEL",
    

    "SHOW_INTRO", 
    
    "ON_ACHIEVEMENT_UPDATE",
    "ON_UNREAD_ACHIEVEMENT",
    "ON_READ_ACHIEVEMENT",
    "ON_ENABLE_ACHIEVEMENT_TOAST",
    "ON_DISABLE_ACHIEVEMENT_TOAST",
    "ON_ACHIEVEMENT_DISPLAY_UPDATE",
    "SHOW_ACHIEVEMENT",
    "OPEN_ACHIEVEMENT_MAIN_PANEL",
    

    
    "ON_BATTLE_PASS_LEVEL_UPDATE",
    "ON_BATTLE_PASS_SEASON_UPDATE",
    "ON_BATTLE_PASS_TRACK_UPDATE",
    "ON_BATTLE_PASS_SHOW_REWARD",
    "ON_BATTLE_PASS_TASK_UPDATE",
    "ON_BATTLE_PASS_TASK_BASIC_INFO_UPDATE",
    "ON_CHANGE_BATTLE_PASS_TAB",
    "ON_BATTLE_PASS_BUY_LEVEL",
    "ON_BATTLE_PASS_TASK_READ_UPDATE",
    "ON_BATTLE_PASS_ADVANCED_BUY_CLOSE",
    "OPEN_BP_WEAPON_CASE",
    

    
    "OPEN_WORLD_ENERGY_POINT_ENTRY",
    "CLOSE_WORLD_ENERGY_POINT_ENTRY",
    "ON_WORLD_ENERGY_POINT_SELECT_TERMS_CHANGED",
    "WORLD_ENERGY_POINT_TRY_START_SETTLEMENT",
    "ON_SHOW_WORLD_ENERGY_POINT_RESULT",
    "ON_WORLD_ENERGY_POINT_START",
    

    
    "ON_OPEN_PROGRESS",
    "ON_INTERRUPT_PROGRESS",
    "ON_CLOSE_PROGRESS",
    "ON_REFRESH_PROGRESS",
    

    
    "TOGGLE_QUICK_MENU_RELEASE_CLOSE",
    "SELECT_QUICK_MENU_SYSTEM",
    

    "ON_CLEAN_CACHE_POOL",
    "ON_GAME_TIME_FREEZE_STATE_CHANGED",
    "ON_ABILITY_UPDATE_SELECTED_TYPE",
}

local msgs = {}
local msgNames = {}
local msgGroups = {
    GlobalMsg = {
        group = GlobalMsg,
    },
}

do
    
    local nextMsgId = 1
    local usedMsgNames = {}
    for k, v in pairs(msgGroups) do
        v.msgIds = {}
        for _, msg in pairs(v.group) do
            local valid = true
            if UNITY_EDITOR or DEVELOPMENT_BUILD then
                if usedMsgNames[msg] then
                    logger.error("Duplicate Msg Name In", k, msg)
                    valid = false
                end
            end
            if valid then
                local id = nextMsgId
                nextMsgId = nextMsgId + 1
                msgs[msg] = id
                msgNames[id] = msg
                usedMsgNames[msg] = true
                v.msgIds[id] = true
            end
        end
        
    end
    logger.info("Msg Check Finished")
end

local const = {
    getMsgName = function(msgId)
        return msgNames[msgId]
    end
}
setmetatable(const, {
    __index = function(_, name)
        
        local res = msgs[name]
        if res == nil then
            logger.error("Msg not in MessageConst: " .. name)
        end
        return res
    end
})
return const
